# Generated by Django 5.1.5 on 2025-04-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_html_alter_article_work_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='creared_at',
            new_name='created_at',
        ),
    ]
